### ISSUE TITLE
Downlink issues

### ISSUE THREAD

**Issue by rudam** [brocaar/lora-packet-multiplexer#2]
Dear Orne,
Can you look at this trouble, please? I have two backends, both with uplink_only = false. Even so, the multiplexer is blocking downlink messages. I compiled the SNAPSHOT-6e3aab3 yesterday (3.0.0).
THX

INFO[0000] starting LoRa Packet Multiplexer              docs="https://www.loraserver.io/" version=SNAPSHOT-6e3aab3
INFO[0000] starting listener                             addr="0.0.0.0:1700"
**INFO[0000] dial udp                                      gateway_id=fcc23dfffe0dd3fa host="127.0.0.1:1701" uplink_only=false
INFO[0000] dial udp                                      gateway_id=fcc23dfffe0dd3fa host="router.eu.thethings.network:1700" uplink_only=false**
INFO[0002] packet received from gateway                  addr="127.0.0.1:44464" gateway_id=fcc23dfffe0dd3fa packet_type=PushData
INFO[0002] sending packet to gateway                     addr="127.0.0.1:44464" gateway_id=fcc23dfffe0dd3fa packet_type=PushACK
INFO[0002] forwarding packet to backend                  from="127.0.0.1:44464" gateway_id=fcc23dfffe0dd3fa packet_type=PushData to="router.eu.thethings.network:1700"
INFO[0002] forwarding packet to backend                  from="127.0.0.1:44464" gateway_id=fcc23dfffe0dd3fa packet_type=PushData to="127.0.0.1:1701"
INFO[0002] packet received from backend                  gateway_id=fcc23dfffe0dd3fa host="127.0.0.1:1701" packet_type=PushACK
INFO[0002] packet received from backend                  gateway_id=fcc23dfffe0dd3fa host="router.eu.thethings.network:1700" packet_type=PushACK
INFO[0005] packet received from gateway                  addr="127.0.0.1:50906" gateway_id=fcc23dfffe0dd3fa packet_type=PullData
INFO[0005] sending packet to gateway                     addr="127.0.0.1:50906" gateway_id=fcc23dfffe0dd3fa packet_type=PullACK
INFO[0005] forwarding packet to backend                  from="127.0.0.1:50906" gateway_id=fcc23dfffe0dd3fa packet_type=PullData to="127.0.0.1:1701"
INFO[0005] forwarding packet to backend                  from="127.0.0.1:50906" gateway_id=fcc23dfffe0dd3fa packet_type=PullData to="router.eu.thethings.network:1700"
INFO[0005] packet received from backend                  gateway_id=fcc23dfffe0dd3fa host="127.0.0.1:1701" packet_type=PullACK
INFO[0005] packet received from backend                  gateway_id=fcc23dfffe0dd3fa host="router.eu.thethings.network:1700" packet_type=PullACK
INFO[0015] packet received from gateway                  addr="127.0.0.1:50906" gateway_id=fcc23dfffe0dd3fa packet_type=PullData
INFO[0015] sending packet to gateway                     addr="127.0.0.1:50906" gateway_id=fcc23dfffe0dd3fa packet_type=PullACK
INFO[0015] forwarding packet to backend                  from="127.0.0.1:50906" gateway_id=fcc23dfffe0dd3fa packet_type=PullData to="127.0.0.1:1701"
INFO[0015] forwarding packet to backend                  from="127.0.0.1:50906" gateway_id=fcc23dfffe0dd3fa packet_type=PullData to="router.eu.thethings.network:1700"
INFO[0015] packet received from backend                  gateway_id=fcc23dfffe0dd3fa host="127.0.0.1:1701" packet_type=PullACK
INFO[0015] packet received from backend                  gateway_id=fcc23dfffe0dd3fa host="router.eu.thethings.network:1700" packet_type=PullACK
INFO[0021] packet received from gateway                  addr="127.0.0.1:42350" gateway_id=fcc23dfffe0dd3fa packet_type=PushData
INFO[0021] sending packet to gateway                     addr="127.0.0.1:42350" gateway_id=fcc23dfffe0dd3fa packet_type=PushACK
INFO[0021] forwarding packet to backend                  from="127.0.0.1:42350" gateway_id=fcc23dfffe0dd3fa packet_type=PushData to="127.0.0.1:1701"
INFO[0021] forwarding packet to backend                  from="127.0.0.1:42350" gateway_id=fcc23dfffe0dd3fa packet_type=PushData to="router.eu.thethings.network:1700"
INFO[0021] packet received from backend                  gateway_id=fcc23dfffe0dd3fa host="127.0.0.1:1701" packet_type=PushACK
INFO[0021] packet received from backend                  gateway_id=fcc23dfffe0dd3fa host="router.eu.thethings.network:1700" packet_type=PushACK
**INFO[0022] packet received from backend                  gateway_id=fcc23dfffe0dd3fa host="127.0.0.1:1701" packet_type=PullResp**
**INFO[0022] ignoring downlink packet, backend is uplink only  gateway_id=fcc23dfffe0dd3fa host="127.0.0.1:1701" packet_type=PullResp**
INFO[0025] packet received from gateway                  addr="127.0.0.1:50906" gateway_id=fcc23dfffe0dd3fa packet_type=PullData
INFO[0025] sending packet to gateway                     addr="127.0.0.1:50906" gateway_id=fcc23dfffe0dd3fa packet_type=PullACK
INFO[0025] forwarding packet to backend                  from="127.0.0.1:50906" gateway_id=fcc23dfffe0dd3fa packet_type=PullData to="127.0.0.1:1701"
INFO[0025] forwarding packet to backend                  from="127.0.0.1:50906" gateway_id=fcc23dfffe0dd3fa packet_type=PullData to="router.eu.thethings.network:1700"
INFO[0025] packet received from backend                  gateway_id=fcc23dfffe0dd3fa host="127.0.0.1:1701" packet_type=PullACK
INFO[0025] packet received from backend                  gateway_id=fcc23dfffe0dd3fa host="router.eu.thethings.network:1700" packet_type=PullACK
I

**Comment by brocaar** [comment]
Could you post your configuration?

**Comment by metadataengine** [comment]
```
[packet_multiplexer]
# Bind
bind="0.0.0.0:1700"

# Backends

[[packet_multiplexer.backend]]
  host="localhost:1701"
  uplink_only=false
  gateway_ids = [
    "fcc23dfffe0dd3fa"
  ]

[[packet_multiplexer.backend]]
  host="router.eu.thethings.network:1700"
  uplink_only=false
  gateway_ids = [
    "fcc23dfffe0dd3fa"
  ]

```

**Comment by rudam** [comment]
```
[packet_multiplexer]
# Bind

bind="0.0.0.0:1700"

# Backends

[[packet_multiplexer.backend]]
  host="localhost:1701"
  uplink_only=false
  gateway_ids = [
    "fcc23dfffe0dd3fa"
  ]

[[packet_multiplexer.backend]]
  host="router.eu.thethings.network:1700"
  uplink_only=false
  gateway_ids = [
    "fcc23dfffe0dd3fa"
  ]

```
